#!/usr/bin/env bash
# Emit symbol graphs for public products and ensure baseline directory is populated.
# Full swift-api-digester semantic diff can be added once baselines are committed.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

BASELINE_DIR="${API_BASELINE_DIR:-Baselines/api}"
mkdir -p "$BASELINE_DIR"

PRODUCTS=(
  CodeEditorCore
  CodeEditorDocuments
  CodeEditorCommands
  CodeEditorWorkspace
  CodeEditorExtensions
  CodeEditorExtensionHost
  CodeEditorLSP
  CodeEditorTasks
  CodeEditorTerminal
  CodeEditorSourceControl
)

if [[ ! -d Grammars/src ]]; then
  echo "Grammars/ missing — bootstrap first" >&2
  exit 1
fi

echo "Building package for symbol graphs…"
swift build >/dev/null

fail=0
for product in "${PRODUCTS[@]}"; do
  dest="$BASELINE_DIR/$product"
  mkdir -p "$dest"
  echo "== $product =="
  if swift build --target "$product" \
      -Xswiftc -emit-symbol-graph \
      -Xswiftc -emit-symbol-graph-dir \
      -Xswiftc "$dest" 2>"$dest/emit.log"; then
    count="$(find "$dest" -name '*.symbols.json' -o -name '*.json' 2>/dev/null | wc -l | tr -d ' ')"
    echo "OK:   $product ($count graph file(s))"
    # Marker for CI: product baseline directory non-empty
    if [[ "$count" -eq 0 ]]; then
      # Some toolchains write different extensions; accept any file besides emit.log
      other="$(find "$dest" -type f ! -name 'emit.log' | wc -l | tr -d ' ')"
      if [[ "$other" -eq 0 ]]; then
        echo "WARN: no graph files for $product (see $dest/emit.log)"
        if [[ "${STRICT_API_BASELINE:-0}" == "1" ]]; then
          fail=1
        fi
      fi
    fi
  else
    echo "WARN: emit failed for $product (see $dest/emit.log)"
    if [[ "${STRICT_API_BASELINE:-0}" == "1" ]]; then
      fail=1
    fi
  fi
done

# Commit-friendly marker listing products
{
  echo "# API baseline products — regenerated by scripts/check-api-baseline.sh"
  date -u +"# %Y-%m-%dT%H:%M:%SZ"
  for product in "${PRODUCTS[@]}"; do
    echo "$product"
  done
} >"$BASELINE_DIR/PRODUCTS.txt"

if [[ "$fail" -ne 0 ]]; then
  echo "API baseline check FAILED"
  exit 1
fi
echo "API baseline check complete under $BASELINE_DIR"
