#!/usr/bin/env bash
# REL-N01 — generate CompatibilityProfile.toml from CI/runtime evidence.
# Do not hand-author "passing" or release-candidate status. This script is the
# source of truth for commit/toolchain/test-suite/artifact IDs.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT="${1:-$ROOT/Docs/Architecture/CompatibilityProfile.toml}"
EVIDENCE_DIR="${EVIDENCE_DIR:-$ROOT/Baselines/evidence}"
mkdir -p "$(dirname "$OUT")" "$EVIDENCE_DIR"

COMMIT="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo "unknown")"
BRANCH="$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")"
SWIFT_VER="$(swift --version 2>&1 | head -1 | tr -d '\n' | sed 's/"/\\"/g')"
XCODE_VER="$(xcodebuild -version 2>/dev/null | tr '\n' ' ' | sed 's/"/\\"/g' || echo "unknown")"
DATE_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
TEST_SUITE_VERSION="swift-testing-package-v1"
ARCHIVE_SHA=""
if [[ -f "$EVIDENCE_DIR/source-archive.sha256" ]]; then
  ARCHIVE_SHA="$(awk '{print $1}' "$EVIDENCE_DIR/source-archive.sha256" | head -1)"
fi
RELEASE_EVIDENCE_ID=""
if [[ -f "$EVIDENCE_DIR/release-evidence.json" ]]; then
  RELEASE_EVIDENCE_ID="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("commit",""))' "$EVIDENCE_DIR/release-evidence.json" 2>/dev/null || true)"
fi
PERF_ARTIFACT=""
if [[ -f "$EVIDENCE_DIR/perf-smoke.json" ]]; then
  PERF_ARTIFACT="Baselines/evidence/perf-smoke.json"
fi

# Qualification axes remain unproven until dedicated S0–S4 jobs write pass artifacts.
# Never invent "passing" here.
SCHEMA_SUPPORT="declared"
SOURCE_COMPAT="unproven"
BEHAVIORAL="unproven"
SECURITY="unproven"
OPERATIONAL="unproven"
if [[ -f "$EVIDENCE_DIR/release-evidence.json" ]]; then
  if python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); sys.exit(0 if d.get("gates",{}).get("tests_passed") else 1)' \
      "$EVIDENCE_DIR/release-evidence.json" 2>/dev/null; then
    # Tests passed evidence exists — still not full S* qualification.
    SOURCE_COMPAT="partial-evidence"
  fi
fi

cat >"$OUT" <<EOF
# CodeEditor Swift-first extension compatibility profile.
# GENERATED by scripts/generate-compatibility-profile.sh — do not hand-author release status.
# REL-N01: honesty-first. Qualification axes are evidence labels, never manual "passing".
# Generated-at: $DATE_UTC

profile = "codeeditor-swift-first-2026"
upstream_commit = "$COMMIT"
branch = "$BRANCH"
manifest_schema = 1
swift_extension_api = "1.0"
status = "pre-alpha"
maturity = "experimental"

[generation]
generator = "scripts/generate-compatibility-profile.sh"
generated_at = "$DATE_UTC"
toolchain_swift = "$SWIFT_VER"
toolchain_xcode = "$XCODE_VER"
test_suite_version = "$TEST_SUITE_VERSION"
artifact_source_archive_sha256 = "$ARCHIVE_SHA"
artifact_release_evidence_commit = "$RELEASE_EVIDENCE_ID"
artifact_perf_smoke = "$PERF_ARTIFACT"
artifact_release_evidence = "Baselines/evidence/release-evidence.json"

# Split qualification (REL-N01). Values are evidence labels, never hand-authored "passing".
[qualification]
schema_support = "$SCHEMA_SUPPORT"
source_compatibility = "$SOURCE_COMPAT"
behavioral_conformance = "$BEHAVIORAL"
security_qualification = "$SECURITY"
operational_qualification = "$OPERATIONAL"

[features]
languages = "experimental"
themes = "experimental"
icon_themes = "experimental"
snippets = "experimental"
language_servers = "experimental"
completion_labels = "experimental"
symbol_labels = "experimental"
debug_adapters = "experimental"
debug_locators = "experimental"
mcp_servers = "experimental"
process_exec = "experimental"
download_file = "experimental"
npm_install = "experimental"
worktree = "experimental"
project = "experimental"
settings = "experimental"
kv_store = "experimental"
documentation_indexing = "experimental"
slash_commands = "experimental"
language_model_provider_metadata = "unsupported"
legacy_agent_server_hosting = "unsupported"

[runtimes]
builtin_swift = "experimental"
data_only = "experimental"
native_process = "experimental"
swift_wasm = "experimental"
remote_provider = "experimental"

# Compatibility levels are NOT "passing" until dedicated CI writes evidence artifacts.
[compatibility_levels]
S0_package = "unproven"
S1_data = "unproven"
S2_swift_api_parity = "unproven"
S3_behavioral = "unproven"
S4_operational = "unproven"
EOF

echo "OK: wrote $OUT (commit=$COMMIT)"
# Mirror a machine-readable stamp for gates.
python3 - "$EVIDENCE_DIR/compatibility-profile-stamp.json" <<PY
import json
json.dump({
  "generated_at": "$DATE_UTC",
  "upstream_commit": "$COMMIT",
  "toolchain_swift": """$SWIFT_VER""",
  "toolchain_xcode": """$XCODE_VER""",
  "test_suite_version": "$TEST_SUITE_VERSION",
  "artifact_source_archive_sha256": "$ARCHIVE_SHA",
  "profile_path": "Docs/Architecture/CompatibilityProfile.toml",
}, open("$EVIDENCE_DIR/compatibility-profile-stamp.json","w"), indent=2)
print("OK: stamp Baselines/evidence/compatibility-profile-stamp.json")
PY
