#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="$ROOT/Docs/Architecture/UNCHECKED-SENDABLE.md"
mkdir -p Baselines Docs/Architecture
rg -n '@unchecked Sendable' Sources --glob '*.swift' | sort > Baselines/unchecked-sendable-current.txt || true
count="$(wc -l < Baselines/unchecked-sendable-current.txt | tr -d ' ')"
{
  echo "# Unchecked Sendable inventory"
  echo
  echo "Generated by \`scripts/generate-unchecked-sendable-inventory.sh\`."
  echo
  echo "Count: **$count** sites under \`Sources/\`."
  echo
  echo "Each site must have an ownership rationale (actor isolation, lock, or documented test-only)."
  echo "New sites require updating \`Baselines/unchecked-sendable-allowlist.txt\`."
  echo
  echo '```'
  cat Baselines/unchecked-sendable-current.txt
  echo '```'
} > "$OUT"
# Seed allowlist if missing
if [[ ! -f Baselines/unchecked-sendable-allowlist.txt ]]; then
  cp Baselines/unchecked-sendable-current.txt Baselines/unchecked-sendable-allowlist.txt
fi
echo "OK: wrote $OUT ($count)"
