#!/usr/bin/env bash
# Resolve immutable commit SHAs (+ parser.c SHA-256) for each grammar and rewrite scripts/grammars.tsv.
#
# Prerequisites: run update-grammars.sh at least once so $TMPDIR/codeeditorview-grammars is populated,
# or pass existing clones. Network may be used if a clone is missing.
#
# Catalog format (Phase 1+):
#   name|c_symbol|url|commit_sha|sha256_parser_c
#
# Usage:
#   ./scripts/record-grammar-pins.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

TSV="scripts/grammars.tsv"
TMP="${TMPDIR:-/tmp}/codeeditorview-grammars"
mkdir -p "$TMP"

if [[ ! -f "$TSV" ]]; then
  echo "error: missing $TSV" >&2
  exit 1
fi

OUT="$(mktemp)"
{
  echo "# name|c_symbol|url|commit_sha|sha256_parser_c"
  echo "# Generated by scripts/record-grammar-pins.sh — do not use mutable branch names as pins."
} >"$OUT"

failures=0
while IFS='|' read -r name c_symbol url ref_or_sha rest; do
  [[ -z "${name:-}" || "$name" =~ ^# ]] && continue
  # Accept old 4-col (ref) or new 5-col rows.
  clone="$TMP/$name"
  if [[ ! -d "$clone/.git" ]]; then
    echo "cloning $name for pin…"
    if ! git clone --filter=blob:none --no-checkout "$url" "$clone" 2>/dev/null; then
      git clone --depth 1 "$url" "$clone" || { echo "fail clone $name" >&2; failures=$((failures + 1)); continue; }
    fi
  fi

  # Prefer current HEAD of clone (what update-grammars last checked out).
  if ! commit="$(git -C "$clone" rev-parse HEAD 2>/dev/null)"; then
    echo "error: no HEAD for $name" >&2
    failures=$((failures + 1))
    continue
  fi
  # Normalize to full SHA
  commit="$(git -C "$clone" rev-parse "$commit")"

  # Locate parser.c for checksum (same layout heuristics as update-grammars.sh).
  srcdir="$clone/src"
  case "$name" in
    typescript) srcdir="$clone/typescript/src" ;;
    tsx) srcdir="$clone/tsx/src" ;;
    markdown) srcdir="$clone/tree-sitter-markdown/src" ;;
    markdown-inline) srcdir="$clone/tree-sitter-markdown-inline/src" ;;
    ocaml)
      [[ -d "$clone/grammars/ocaml/src" ]] && srcdir="$clone/grammars/ocaml/src"
      [[ -d "$clone/ocaml/src" ]] && srcdir="$clone/ocaml/src"
      ;;
    php) [[ -d "$clone/php/src" ]] && srcdir="$clone/php/src" ;;
  esac

  # Ensure tree is present for checksum
  if [[ ! -f "$srcdir/parser.c" ]]; then
    git -C "$clone" checkout -q "$commit" 2>/dev/null || true
    # sparse-ish: checkout files if missing
    if [[ ! -f "$srcdir/parser.c" ]]; then
      git -C "$clone" checkout -q "$commit" -- . 2>/dev/null || true
    fi
  fi

  sha256="-"
  if [[ -f "$srcdir/parser.c" ]]; then
    if command -v shasum >/dev/null 2>&1; then
      sha256="$(shasum -a 256 "$srcdir/parser.c" | awk '{print $1}')"
    elif command -v sha256sum >/dev/null 2>&1; then
      sha256="$(sha256sum "$srcdir/parser.c" | awk '{print $1}')"
    fi
  fi

  echo "${name}|${c_symbol}|${url}|${commit}|${sha256}" >>"$OUT"
  echo "pinned $name @ ${commit:0:12} sha256=${sha256:0:12}…"
done <"$TSV"

if [[ "$failures" -gt 0 ]]; then
  echo "record-grammar-pins failed with $failures error(s)" >&2
  rm -f "$OUT"
  exit 1
fi

mv "$OUT" "$TSV"
echo
echo "Wrote immutable pins to $TSV"
echo "Validate with: ./scripts/check-grammar-pins.sh"
